service: aws-proba

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  profile: serverlessUser
  region: eu-central-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
        - sns:Subscribe
      Resource:
        - arn:aws:sns:eu-central-1:275505252693:ProbaTopic
    - Effect: Allow
      Action:
        - ses:*
      Resource: 
        - arn:aws:ses:eu-central-1:275505252693:identity/aws.tim6@gmail.com

functions:
  publish:
    handler: sns.publish
    package:
      patterns:
        - 'sns.py'
    events:
      - http:
          path: publish
          method: GET
          cors: true

  subscribe:
    handler: sns.subscribe
    package:
      patterns:
        - 'sns.py'
    events:
      - http:
          path: subscribe
          method: GET
          cors: true

  sendEmail:
    handler: ses.send_email
    package:
      patterns:
        - 'ses.py'
    events:
      - http:
          path: send-email
          method: POST
          cors: true

resources:
  Resources:
    SNSProbaTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ProbaTopic

    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: aws.tim6@gmail.com
        Protocol: email
        TopicArn: {"Ref": "SNSProbaTopic"}

    SESIdentity:
      Type: AWS::SES::EmailIdentity
      Properties: 
        EmailIdentity: aws.tim6@gmail.com

