service: aws-tim6

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  profile: serverlessUser
  region: eu-central-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: GET
          cors: true
resources:
  Resources:
    projekat6:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: projekat6
    filesMetadata:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: filesMetadata
        AttributeDefinitions:
          - AttributeName: object_key
            AttributeType: S
        KeySchema:
          - AttributeName: object_key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
